### ISSUE TITLE
Provider directory check broken

### ISSUE THREAD

**Issue by cuthbert** [php-edifact/edifact-mapping#5]
The directory format check is broken. In version 0.2 the following method also contained a check for directories starting with 'D'. Now it will prepend D to valid directories like D96A, which results in DD96A.

MappingProvider:
`    
public function checkDirectoryFormat($directory)
    {
        if (preg_match('/\d{2}[A-C]{1}/', $directory)) {
            return 'D'.$directory;
        }
        
        return $directory;
    }
`    

Since I don't know the reason of the removal, it should be checked somehow.

(commit 2161772807594d57bdb3d66421339ed82dbf7d7d)

**Comment by sabas** [comment]
Perhaps the regex should be changed as ```/^\d{2}[A-C]{1}$/```
could you please test this solution?

I made that change when I added a mapping for WESTIM, which don't follow the directory format.

**Comment by cuthbert** [comment]
Yep, this works.

**Comment by sabas** [comment]
Do you want to do a PR? :-)

**Comment by cuthbert** [comment]
Yes, I'll do it. :)
