### ISSUE TITLE
D99B DTM segment is incomplete

### ISSUE THREAD

**Issue by mahsa92** [php-edifact/edifact-mapping#9]
@sabas Thanks for the work you put into this.
According to [https://service.unece.org/trade/untdid/d99b/trcd/trcdc507.htm](url), DTM segment is incomplete.

https://github.com/php-edifact/edifact-mapping/blob/6ee33bb3326fa32ec5ebede94def4d4a83d728e8/src/Mapping/D99B/segments.xml#L526

Proposed change:
        
       <segment id="DTM" name="date/time/period" desc="To specify date, and/or time, or period.">     
            <composite_data_element id="C507" required="true" name="datetimeperiod" desc="Date and/or time, or period relevant to the specified date/time/period type.">
                <data_element id="2005" required="true" name="datetimeperiodQualifier" desc="Code giving specific meaning to a date, time or period." type="an" maxlength="3"/>
                <data_element id="2380" name="datetimeperiod" desc="The value of a date, a date and time, a time or of a period in a specified representation." type="an" maxlength="35"/>
                <data_element id="2379" name="datetimeperiodFormatQualifier" desc="Specification of the representation of a date, a date and time or of a period." type="an" maxlength="3"/>
              </composite_data_element>
         </segment>

**Comment by sabas** [comment]
Thanks,
I've merged it although it should be investigated why the parser failed to extract those lines :-)

**Comment by sabas** [comment]
@mahsa92 @davidvandertuijn @denys-chernogorov Hello, I just wanted to notify you I found a fix for the xml and I regenerated most of the editions!
